package com.example.c_tracker

import android.Manifest

val REQUIRED_PERMISSIONS = arrayOf(Manifest.permission.ACCESS_COARSE_LOCATION)
val PERMISSION_REQUEST_CODE = 1000
val PREF_CODE_NAME = mapOf(
    "01" to "北海道",
    "02" to "青森県",
    "03" to "岩手県",
    "04" to "宮城県",
    "05" to "秋田県",
    "06" to "山形県",
    "07" to "福島県",
    "08" to "茨城県",
    "09" to "栃木県",
    "10" to "群馬県",
    "11" to "埼玉県",
    "12" to "千葉県",
    "13" to "東京都",
    "14" to "神奈川県",
    "15" to "新潟県",
    "16" to "富山県",
    "17" to "石川県",
    "18" to "福井県",
    "19" to "山梨県",
    "20" to "長野県",
    "21" to "岐阜県",
    "22" to "静岡県",
    "23" to "愛知県",
    "24" to "三重県",
    "25" to "滋賀県",
    "26" to "京都府",
    "27" to "大阪府",
    "28" to "兵庫県",
    "29" to "奈良県",
    "30" to "和歌山県",
    "31" to "鳥取県",
    "32" to "島根県",
    "33" to "岡山県",
    "34" to "広島県",
    "35" to "山口県",
    "36" to "徳島県",
    "37" to "香川県",
    "38" to "愛媛県",
    "39" to "高知県",
    "40" to "福岡県",
    "41" to "佐賀県",
    "42" to "長崎県",
    "43" to "熊本県",
    "44" to "大分県",
    "45" to "宮崎県",
    "46" to "鹿児島県",
    "47" to "沖縄県"
)
